---
- hosts: all
  vars: 
    py3env: /home/vagrant/py3env
#    project_home: /srv/django/projects/portfolio
  tasks:
  - name: apt-get update
    apt: update_cache=yes
    sudo: yes
  - apt: pkg=vim
    sudo: yes
  - apt: pkg=python-pip
    sudo: yes
  - apt: pkg=python3
    sudo: yes
  - apt: pkg=python3-dev
    sudo: yes
  - pip: name=virtualenv
    sudo: yes
  - name: create virtualenv
    command: virtualenv -p /usr/bin/python3 {{ py3env }}
             creates={{ py3env }}
  - name: install ipython into virtualenv
    pip: name=ipython
         virtualenv={{ py3env }}
  - name: install project requirements
    pip: requirements=/vagrant/requirements.txt
         virtualenv={{ py3env }}

  - name: add automatic activation of virtualenv to .bashrc
    lineinfile: dest=/home/vagrant/.bashrc
                line=". {{ py3env }}/bin/activate"
  - lineinfile: dest=/home/vagrant/.bashrc
                line='cd /vagrant'

#  - django_manage: app_path=/vagrant
#                   command=syncdb
#                   virtualenv={{ py3env }}
#  - command: /home/vagrant/py3env/bin/python manage.py populate_demo_data
#             chdir=/vagrant

### some requirements manually debugged/found and added, not sure if correct, just trial and error to get project working
#  - pip: name=pillow
#         virtualenv={{ py3env }}

#  - name: create project folder
#    file: path={{ project_home }}
#          state=directory
#          owner=martin
#          group=www-admin
#          mode=0755
#    sudo: yes
#  - git: repo=https://github.com/martflu/amanaman.git
#         dest=/srv/django/projects/portfolio
#         sudo: yes
#         sudo_user: martin
#  - name: install requirements
#    pip: requirements=requirements.txt virtualenv={{ py3env }}
